### PR TITLE
* Add support for a modules table to store module meta-data

### PR DESCRIPTION
**Pull request by xorrkaz**
- Add options to suppress and only print SQLite3 schema
- Store some node properties as serialized JSON for easy printing
- Store the node description as a separate field for better searching
- Support writing output to a file

### CODE REVIEW

**Comment by cmoberg** [comment]
The original intent of the plugin was to generate an index purely for free-text searching the content of the module catalog. And to have the actual data available as part of the module catalog itself, so not sure why we want/need it in a separate table here. Would prefer to not duplicate. But you may have other, more evil motives than I realize :-)

**Comment by xorrkaz** [comment]
On 10/17/16 13:33, Carl Moberg wrote:

> The original intent of the plugin was to generate an index purely for
> free-text searching the content of the module catalog. And to have the
> actual module catalog data available as part of the module catalog
> itself, so not sure why we want/need it in a separate table here. Would
> prefer to not duplicate. But you may have other, more evil motives than
> I realize :-)

Having the module table allows me to have a cached way to call into the 
catalog.  At the very least, given a node, I need its module name and 
org.  I figured it was easier to keep this in a separate table rather 
than have that data duplicated per node in the yindex table.

I guess I don't need the prefix, ns, and maturity stuff in this DB 
provided I can get it from the catalog.  But for the moment, I can't. 
so I envision this module evolving over time to remove some of the 
overlap with the catalog as the catalog matures.

Joe

**Comment by cmoberg** [comment]
> Having the module table allows me to have a cached way to call into the
> catalog.  At the very least, given a node, I need its module name and
> org.  I figured it was easier to keep this in a separate table rather
> than have that data duplicated per node in the yindex table.
> 
> I guess I don't need the prefix, ns, and maturity stuff in this DB
> provided I can get it from the catalog.  But for the moment, I can't.
> so I envision this module evolving over time to remove some of the
> overlap with the catalog as the catalog matures.

 Got it. So how about this. We add an option `--yang-catalog-index-module-cache` (or something slightly more snappy) that produces a second table with module name-to-org mapping?

**Comment by xorrkaz** [comment]
On 10/17/16 16:15, Carl Moberg wrote:

> ```
> Having the module table allows me to have a cached way to call into the
> catalog. At the very least, given a node, I need its module name and
> org. I figured it was easier to keep this in a separate table rather
> than have that data duplicated per node in the yindex table.
> 
> I guess I don't need the prefix, ns, and maturity stuff in this DB
> provided I can get it from the catalog. But for the moment, I can't.
> so I envision this module evolving over time to remove some of the
> overlap with the catalog as the catalog matures.
> ```
> 
> Got it. So how about this. We add an option
> |--yang-catalog-index-module-cache| (or something slightly more snappy)
> that produces a second table with module name-to-org mapping?

Sure, I can do that.  But without that mapping, it will be very hard to 
do the lookup in the catalog.

What would be cool is if you could add a status to all of the IETF 
modules in the catalog to reflect RFC or DRAFT so I can use that instead 
of the local cache.

Joe

**Comment by cmoberg** [comment]
> Got it. So how about this. We add an option
>  |--yang-catalog-index-module-cache| (or something slightly more snappy)
>  that produces a second table with module name-to-org mapping?
> Sure, I can do that.  But without that mapping, it will be very hard to
> do the lookup in the catalog.

Agreed! So how about an option to the plugin `--yang-module-catalog-org` with the value of the organization and add that straight into yindex or module table?

> What would be cool is if you could add a status to all of the IETF
> modules in the catalog to reflect RFC or DRAFT so I can use that instead
> of the local cache.

Same thing here. Probably don't want to hardcode that into the module-catalog plugin (as it is supposed to be general), but perhaps as a general option to hardcode a specific field in the output. I'll go work on that.

**Comment by xorrkaz** [comment]
On 10/17/16 16:15, Carl Moberg wrote:

> ```
> Having the module table allows me to have a cached way to call into the
> catalog. At the very least, given a node, I need its module name and
> org. I figured it was easier to keep this in a separate table rather
> than have that data duplicated per node in the yindex table.
> 
> I guess I don't need the prefix, ns, and maturity stuff in this DB
> provided I can get it from the catalog. But for the moment, I can't.
> so I envision this module evolving over time to remove some of the
> overlap with the catalog as the catalog matures.
> ```
> 
> Got it. So how about this. We add an option
> |--yang-catalog-index-module-cache| (or something slightly more snappy)
> that produces a second table with module name-to-org mapping?

I did another PR with the new option and a bug fix.

Joe

**Pull request closed without merging**
